import 'dart:typed_data';

import 'package:certificate_crypto/certificate_crypto.dart';
import 'package:image/image.dart' as img;
import 'package:zxing2/qrcode.dart';

Map<String, dynamic>? decodeQrRecord(List<int> bytes) {
  try {
    final decoded = img.decodeImage(Uint8List.fromList(bytes));
    if (decoded == null) return null;
    final reader = QRCodeReader();
    final hints = DecodeHints()
      ..put(DecodeHintType.tryHarder)
      ..put(DecodeHintType.possibleFormats, [BarcodeFormat.qrCode]);
    final grayscale = img.grayscale(decoded);
    final variants = <img.Image>[
      decoded,
      grayscale,
      img.adjustColor(grayscale, contrast: 1.35),
      img.invert(grayscale),
      img.copyResize(grayscale, width: decoded.width * 2),
      img.copyRotate(grayscale, angle: 90),
      img.copyRotate(grayscale, angle: 180),
      img.copyRotate(grayscale, angle: 270),
    ];
    // A certificate QR is often small relative to the page. Decode
    // overlapping tiles as well as the full page so text and background
    // detail cannot prevent the detector from finding its finder patterns.
    final tileWidth = (decoded.width * .55)
        .round()
        .clamp(96, decoded.width)
        .toInt();
    final tileHeight = (decoded.height * .55)
        .round()
        .clamp(96, decoded.height)
        .toInt();
    final xStep = ((decoded.width - tileWidth) / 2)
        .round()
        .clamp(1, decoded.width)
        .toInt();
    final yStep = ((decoded.height - tileHeight) / 2)
        .round()
        .clamp(1, decoded.height)
        .toInt();
    for (var y = 0; y < decoded.height; y += yStep) {
      for (var x = 0; x < decoded.width; x += xStep) {
        final left = x.clamp(0, decoded.width - tileWidth).toInt();
        final top = y.clamp(0, decoded.height - tileHeight).toInt();
        variants.add(
          img.copyCrop(
            grayscale,
            x: left,
            y: top,
            width: tileWidth,
            height: tileHeight,
          ),
        );
        if (x + tileWidth >= decoded.width &&
            y + tileHeight >= decoded.height) {
          break;
        }
      }
      if (y + tileHeight >= decoded.height) break;
    }
    for (final variant in variants) {
      // zxing2's RGBLuminanceSource expects ARGB values from an RGBA byte
      // stream. Passing BGRA here reverses the color channels and makes the
      // detector unreliable even for QR codes generated by this app.
      final rgba = variant
          .convert(numChannels: 4)
          .getBytes(order: img.ChannelOrder.rgba);
      final source = RGBLuminanceSource(
        variant.width,
        variant.height,
        rgba.buffer.asInt32List(),
      );
      for (final binarizer in [
        GlobalHistogramBinarizer(source),
        HybridBinarizer(source),
      ]) {
        try {
          final result = reader.decode(BinaryBitmap(binarizer), hints: hints);
          return decodeVerificationQrPayload(result.text);
        } catch (_) {
          // Continue through the remaining image preprocessing variants.
        }
      }
    }
    return null;
  } catch (_) {
    return null;
  }
}
