part of 'app_localizations.dart';

const _en = <String, String>{
  'Project workspace': 'Project workspace',
  'Manage projects and import existing workspaces.':
      'Manage projects and import existing workspaces.',
  'Projectworkspace': 'Projectworkspace',
  'New project': 'New project',
  'Import project': 'Import project',
  'Recent projects': 'Recent projects',
  'Your workspace': 'Your workspace',
  'Create project': 'Create project',
  'Create your first project': 'Create your first project',
  'Start with project information, then add a template and record data.':
      'Start with project information, then add a template and record data.',
  'No projects have been created yet.': 'No projects have been created yet.',
  'Offline ready': 'Offline ready',
  'Draft': 'Draft',
  'Verify certificate': 'Verify certificate',
  'Use the certificate file itself. Verification runs offline from its embedded security record.':
      'Use the certificate file itself. Verification runs offline from its embedded security record.',
  'Certificate file': 'Certificate file',
  'Select an issued certificate. For PNG/JPG images, the QR code is extracted automatically and the result reports extraction success or failure.':
      'Select an issued certificate. For PNG/JPG images, the QR code is extracted automatically and the result reports extraction success or failure.',
  'Select certificate file': 'Select certificate file',
  'QR verification': 'QR verification',
  'Scan the QR code with your device and paste its cstudio:// payload here.':
      'Scan the QR code with your device and paste its cstudio:// payload here.',
  'QR payload': 'QR payload',
  'Verify QR payload': 'Verify QR payload',
  'Certificate ID': 'Certificate ID',
  'Additional lookup method for certificates already available in this offline workspace.':
      'Additional lookup method for certificates already available in this offline workspace.',
  'Verify certificate ID': 'Verify certificate ID',
  'certificate-…': 'certificate-…',
  'Certificate library': 'Certificate library',
  'Export all': 'Export all',
  'Export project': 'Export project',
  'Export the background, font, data, and field positions.':
      'Export the background, font, data, and field positions.',
  'Record data': 'Record data',
  'Export all PNG files (ZIP)': 'Export all PNG files (ZIP)',
  'Export all PDF files (ZIP)': 'Export all PDF files (ZIP)',
  'Generated certificates': 'Generated certificates',
  'Browse, preview, verify, and export the actual generated certificate files.':
      'Browse, preview, verify, and export the actual generated certificate files.',
  'Search by recipient, certificate ID, or project':
      'Search by recipient, certificate ID, or project',
  'signed': 'signed',
  'Signed': 'Signed',
  'valid': 'valid',
  'failed': 'failed',
  'pending': 'pending',
  'generating': 'generating',
  'generated': 'generated',
  'Recipient unavailable': 'Recipient unavailable',
  'Certificate Studio': 'Certificate Studio',
  'Certificate preview': 'Certificate preview',
  'Certificate export settings': 'Certificate export settings',
  'Choose file name field': 'Choose file name field',
  'Field used for the file name': 'Field used for the file name',
  'Archive style': 'Archive style',
  'All files in one ZIP': 'All files in one ZIP',
  'ZIP per certificate with signature.txt':
      'ZIP per certificate with signature.txt',
  'Certificate details': 'Certificate details',
  'Recipient': 'Recipient',
  'Status': 'Status',
  'Available': 'Available',
  'Unavailable': 'Unavailable',
  'Security': 'Security',
  'Valid signature': 'Valid signature',
  'Verification failed': 'Verification failed',
  'The certificate is authentic.': 'The certificate is authentic.',
  'Unable to verify.': 'Unable to verify.',
  'View': 'View',
  'Export PNG': 'Export PNG',
  'Export PDF': 'Export PDF',
  'Export PNG ZIP': 'Export PNG ZIP',
  'Export PDF ZIP': 'Export PDF ZIP',
  'No certificates match your search.': 'No certificates match your search.',
  'No certificates generated yet.': 'No certificates generated yet.',
  'Field properties': 'Field properties',
  'Position and size': 'Position and size',
  'Select a template before designing this certificate.':
      'Select a template before designing this certificate.',
  'Import recipient data first so fields can be mapped to columns.':
      'Import recipient data first so fields can be mapped to columns.',
  'Unsaved changes': 'Unsaved changes',
  'Saved': 'Saved',
  'Saving...': 'Saving...',
  'Template name': 'Template name',
  'Background image': 'Background image',
  'Choose image': 'Choose image',
  'DPI': 'DPI',
  'Choose a certificate template': 'Choose a certificate template',
  'Template library': 'Template library',
  'Add template': 'Add template',
  'Use template': 'Use template',
  'Edit template': 'Edit template',
  'Selected': 'Selected',
  'In use': 'In use',
  'Use': 'Use',
  'Import font': 'Import font',
  'Font library': 'Font library',
  'Manage fonts available to projects.': 'Manage fonts available to projects.',
  'Live font preview': 'Live font preview',
  'Write a sample to compare how every imported font renders it.':
      'Write a sample to compare how every imported font renders it.',
  'Preview text': 'Preview text',
  'Generate certificates': 'Generate certificates',
  'Create signed PDF and high-resolution PNG certificates with offline verification records.':
      'Create signed PDF and high-resolution PNG certificates with offline verification records.',
  'Ready to generate': 'Ready to generate',
  'Generating certificates…': 'Generating certificates…',
  'Open certificate library': 'Open certificate library',
  'Certificate is authentic': 'Certificate is authentic',
  'The signature and document hash are valid.':
      'The signature and document hash are valid.',
  'The requested file is unavailable.': 'The requested file is unavailable.',
  'Certificate exported successfully.': 'Certificate exported successfully.',
  'No generated files were available to export.':
      'No generated files were available to export.',
  'Field used for the exported file name':
      'Field used for the exported file name',
  'Verification QR': 'Verification QR',
  'Set up your institution': 'Set up your institution',
  'Continue to workspace': 'Continue to workspace',
  'Add record data': 'Add record data',
  'Import an .xlsx workbook or paste a spreadsheet. The first row becomes the column names.':
      'Import an .xlsx workbook or paste a spreadsheet. The first row becomes the column names.',
  'Paste table data': 'Paste table data',
  'Choose Excel file': 'Choose Excel file',
  'Paste from clipboard': 'Paste from clipboard',
  'Import data': 'Import data',
  'Data preview': 'Data preview',
  'Fields': 'Fields',
  'fields detected': '{count} fields detected',
  'Add field': 'Add field',
  'Edit field': 'Edit field',
  'Delete field': 'Delete field',
  'Field name': 'Field name',
  'Field name must be unique and not empty.':
      'Field name must be unique and not empty.',
  'At least one field is required.': 'At least one field is required.',
  'Edit record': 'Edit record',
  'Record row {number}': 'Record row {number}',
  'Detected fixed values': 'Choose one of the detected values',
  'Value must be between {min} and {max}.':
      'Value must be between {min} and {max}.',
  'Editable record rows': 'Editable record rows',
  'Add record row': 'Add record row',
  'Delete record row': 'Delete record row',
  'Edit value': 'Edit value',
  'Row actions': 'Row actions',
  'No recipient data yet. Import a table to continue to certificate design.':
      'No recipient data yet. Import a table to continue to certificate design.',
  'Certificate type': 'Certificate type',
  'Creating...': 'Creating...',
  'Create new project': 'Create new project',
  'Delete project': 'Delete project',
  'Organization settings': 'Organization settings',
  'Control center': 'Control center',
  'Appearance & language': 'Appearance & language',
  'Application language': 'Application language',
  'Arabic': 'Arabic',
  'English': 'English',
  'Color mode': 'Color mode',
  'System': 'System',
  'Light': 'Light',
  'Dark': 'Dark',
  'Brand color': 'Brand color',
  'Open color picker': 'Open color picker',
  'Primary color': 'Primary color',
  'Choose custom color': 'Choose custom color',
  'Electronic signature': 'Electronic signature',
  'Export institution profile': 'Export institution profile',
  'Import institution profile': 'Import institution profile',
  'Export signatures': 'Export signatures',
  'Import signatures': 'Import signatures',

  'localWorkspaceUnavailable': 'Local workspace is unavailable.',
  'home': 'Home',
  'projects': 'Projects',
  'templates': 'Templates',
  'fonts': 'Fonts',
  'certificates': 'Certificates',
  'verification': 'Verification',
  'settings': 'Settings',
  'workspace': 'Workspace',
  'createManageCertificates': 'Create and manage your certificates',
  'offlineReady': 'Offline ready',
  'notifications': 'Notifications',
  'verify': 'Verify',
  'Open navigation': 'Open navigation',
  'newProject': 'New project',
  'importProject': 'Import project',
  'recentProjects': 'Recent projects',
  'yourWorkspace': 'Your workspace',
  'createFirstProject': 'Create your first project',
  'firstProjectDescription':
      'Start with project information, then add a template and record data.',
  'createProject': 'Create project',
  'failedLoadProjects': 'Failed to load projects. Please try again.',
  'verifyCertificate': 'Verify certificate',
  'selectCertificateFile': 'Select certificate file',
  'certificateFile': 'Certificate file',
  'qrVerification': 'QR verification',
  'certificateId': 'Certificate ID',
  'verifyQrPayload': 'Verify QR payload',
  'verifyCertificateId': 'Verify certificate ID',
  'qrPayload': 'QR payload',
  'cancel': 'Cancel',
  'save': 'Save',
  'close': 'Close',
  'delete': 'Delete',
  'addDataField': 'Add data field',
  'select': 'Select',
  'search': 'Search',
  'success': 'Success',
  'error': 'Error',
  'continue': 'Continue',
  'back': 'Back',
  'persistedFonts': '{count} persisted fonts available to projects.',
  'This information is used to identify your certificates and verification records.':
      'This information is used to identify your certificates and verification records.',
  'A private institution key will be generated and kept behind secure storage. It is never displayed or written into the project package.':
      'A private institution key will be generated and kept behind secure storage. It is never displayed or written into the project package.',
  'Institution name is required.': 'Institution name is required.',
  'Project information': 'Project information',
  'Set up the context for this certificate-issuing project. You can configure templates and data next.':
      'Set up the context for this certificate-issuing project. You can configure templates and data next.',
  'Project name is required.': 'Project name is required.',
  'Training': 'Training',
  'Achievement': 'Achievement',
  'Participation': 'Participation',
  'Custom': 'Custom',
  'Continue': 'Continue',
  'Configure this project, then design and generate certificates.':
      'Configure this project, then design and generate certificates.',
  'Choose the certificate background.': 'Choose the certificate background.',
  'Import or paste recipient data.': 'Import or paste recipient data.',
  'Choose the font available to this project.':
      'Choose the font available to this project.',
  'Place fields on the certificate canvas.':
      'Place fields on the certificate canvas.',
  'Create certificates after setup is complete.':
      'Create certificates after setup is complete.',
  'Not set': 'Not set',
  'The certificate could not be verified.':
      'The certificate could not be verified.',
  'Success — QR payload was extracted from the image':
      'Success — QR payload was extracted from the image',
  'Failed — no readable QR code was found':
      'Failed — no readable QR code was found',
  'Hash matches embedded certificate data':
      'Hash matches embedded certificate data',
  'Valid Ed25519 signature': 'Valid Ed25519 signature',
  'Not provided': 'Not provided',
  'Certificate template': 'Certificate template',
  'Template image unavailable': 'Template image unavailable',
  'Please select a PDF, PNG, JPG, or JPEG certificate.':
      'Please select a PDF, PNG, JPG, or JPEG certificate.',
  'Create and manage your certificates': 'Create and manage your certificates',
  'Failed to load projects. Please try again.':
      'Failed to load projects. Please try again.',
  'projectUpdated': '{course}  •  Updated {date}',
  'Certificate project': 'Certificate project',
  'persistedProjects': '{count} persisted projects',
  'createdDate': 'Created {date}',
  'This permanently removes the project, recipient data, design, generated certificates, verification records, and project key.':
      'This permanently removes the project, recipient data, design, generated certificates, verification records, and project key.',
  'tableDataExample': 'Field 1\tField 2\tField 3\nValue 1\tValue 2\tValue 3',
  'Choose a background image from your device, preview it, and use it as this project’s certificate canvas.':
      'Choose a background image from your device, preview it, and use it as this project’s certificate canvas.',
  'Browse persisted certificate backgrounds or import a new template.':
      'Browse persisted certificate backgrounds or import a new template.',
  'No templates saved yet. Add a PNG, JPG, or WEBP background image to continue.':
      'No templates saved yet. Add a PNG, JPG, or WEBP background image to continue.',
  'File not found at saved path': 'File not found at saved path',
  'Required': 'Required',
  'Valid certificate': 'Valid certificate',
  'Integrity compromised': 'Integrity compromised',
  'Invalid signature': 'Invalid signature',
  'Unknown certificate': 'Unknown certificate',
  'Verification data missing': 'Verification data missing',
  'Unsupported or malformed certificate':
      'Unsupported or malformed certificate',
  'QR extraction failed and no embedded verification record was found in the image.':
      'QR extraction failed and no embedded verification record was found in the image.',
  'We could not save your institution. Please try again.':
      'We could not save your institution. Please try again.',
  'We could not create this project. Please try again.':
      'We could not create this project. Please try again.',
  'Certificate was not found in this offline workspace.':
      'Certificate was not found in this offline workspace.',
  'The QR payload is malformed or uses an unsupported protocol.':
      'The QR payload is malformed or uses an unsupported protocol.',
  'This template is used by a project and cannot be deleted.':
      'This template is used by a project and cannot be deleted.',
  'We could not import this workbook.': 'We could not import this workbook.',
  'The exported file was not written.': 'The exported file was not written.',
  'SQLCipher persistence is not available on Flutter Web.':
      'SQLCipher persistence is not available on Flutter Web.',
  'e.g. Al-Noor Academy': 'e.g. Al-Noor Academy',
  'e.g. Flutter Advanced Course 2026': 'e.g. Flutter Advanced Course 2026',
  'e.g. Flutter Advanced': 'e.g. Flutter Advanced',
  'No certificates generated yet. Import recipient data, design the layout, then generate.':
      'No certificates generated yet. Import recipient data, design the layout, then generate.',
  'Choose file': 'Choose file',
};
